name: CD - Docker Backend

on:
  push:
    branches:
      - main
      - desenvolvimento

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Gerar tags da imagem
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: carolinesant/blog
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value={{branch}},enable={{is_branch}}

      - name: Build e push da imagem
        uses: docker/build-push-action@v5
        with:
          context: Backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
